# Generated by Django 5.2.1 on 2025-05-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('type', models.CharField(choices=[('income', 'Przychód'), ('expense', 'Wydatek')], default='expense', max_length=10, verbose_name='Typ')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('date', models.DateField(verbose_name='Data')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Kategoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Transakcja',
                'verbose_name_plural': 'Transakcje',
                'ordering': ['-date'],
            },
        ),
    ]
